version: '3.7'

services:
    currency-exchange:
        image: neerajkumar/currency-currency-exchange-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8001:8001"
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka

    currency-conversion:
        image: neerajkumar/currency-currency-conversion-service:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8100:8100"
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
    
    api-gateway:
        image: neerajkumar/currency-api-gateway:0.0.1-SNAPSHOT
        mem_limit: 700m
        ports:
            - "8765:8765"
        networks:
            - currency-network
        depends_on:
            - naming-server
        environment:
            eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka

    naming-server:
        image: neerajkumar/currency-naming-server:0.0.1-SNAPSHOT
        container_name: naming-server
        mem_limit: 700m
        ports:
            - "8761:8761"
        networks:
            - currency-network

networks:
    currency-network:
